.TH "Audiomanager" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audiomanager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AudioSource \fBcarsound\fP"
.br
.RI "\fIThe carsound Function\&. \fP"
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "AudioSource Audiomanager\&.carsound"

.PP
The carsound Function\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
