.TH "carposition" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
carposition \- Car position in First scene\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject[] \fBcars\fP"
.br
.ti -1c
.RI "float \fBmaxpos\fP = 2\&.0f"
.br
.ti -1c
.RI "float \fBdelayTimer\fP = 1f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Car position in First scene\&. 


.SH "Member Data Documentation"
.PP 
.SS "GameObject [] carposition\&.cars"

.SS "float carposition\&.delayTimer = 1f"

.SS "float carposition\&.maxpos = 2\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
