.TH "change_obj" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
change_obj \- Change_obj for scene\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnclick\fP ()"
.br
.RI "\fIRaises the event on Click\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBObject1\fP"
.br
.ti -1c
.RI "GameObject \fBObject2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Change_obj for scene\&. 


.SH "Member Function Documentation"
.PP 
.SS "void change_obj\&.Onclick ()"

.PP
Raises the event on Click\&. 
.SH "Member Data Documentation"
.PP 
.SS "GameObject change_obj\&.Object1"

.SS "GameObject change_obj\&.Object2"


.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
