.TH "change_obj.cs" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
change_obj.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBchange_obj\fP"
.br
.RI "\fIChange_obj for scene\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
