.TH "Dontgothroughwall.js" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dontgothroughwall.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBAwake\fP ()"
.br
.ti -1c
.RI "function \fBFixedUpdate\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBlayerMask\fP"
.br
.ti -1c
.RI "var \fBskinWidth\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function Awake ()"

.SS "function FixedUpdate ()"

.SH "Variable Documentation"
.PP 
.SS "var layerMask"

.SS "var skinWidth"

.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
