.TH "Highscore" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Highscore \- High score show\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBhighscore\fP"
.br
.ti -1c
.RI "int \fBprescore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
High score show\&. 


.SH "Member Data Documentation"
.PP 
.SS "Text Highscore\&.highscore"

.SS "int Highscore\&.prescore"


.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
