.TH "move" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
move \- Move\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBcar_speed\fP"
.br
.ti -1c
.RI "float \fBmax_position\fP = 2\&.2f"
.br
.ti -1c
.RI "\fBUImanager\fP \fBui\fP"
.br
.ti -1c
.RI "\fBAudiomanager\fP \fBam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Move\&. 


.SH "Member Data Documentation"
.PP 
.SS "\fBAudiomanager\fP move\&.am"

.SS "float move\&.car_speed"

.SS "float move\&.max_position = 2\&.2f"

.SS "\fBUImanager\fP move\&.ui"


.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
