.TH "Quit" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quit \- for \fBQuit\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnClick\fP ()"
.br
.RI "\fIRaises the click event\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
for \fBQuit\fP\&. 


.SH "Member Function Documentation"
.PP 
.SS "void Quit\&.OnClick ()"

.PP
Raises the click event\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
