.TH "timer" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timer \- Timer\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBcounterText\fP"
.br
.ti -1c
.RI "float \fBseconds\fP"
.br
.ti -1c
.RI "float \fBtotal_time\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBgame_end\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timer\&. 


.SH "Member Data Documentation"
.PP 
.SS "Text timer\&.counterText"

.SS "bool timer\&.game_end\fC [static]\fP"

.SS "float timer\&.seconds"

.SS "float timer\&.total_time"


.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
