.TH "win" 3 "Tue Apr 26 2016" "FLASH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
win \- Win collider \&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBGameover\fP"
.br
.ti -1c
.RI "GameObject \fBWinner\fP"
.br
.ti -1c
.RI "GameObject \fBCar\fP"
.br
.ti -1c
.RI "GameObject \fBenemy\fP"
.br
.ti -1c
.RI "\fBcarmoveinmap\fP \fBcarmove\fP"
.br
.ti -1c
.RI "\fBUImanager\fP \fBui\fP"
.br
.ti -1c
.RI "\fBtimer\fP \fBtimescript\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Win collider \&. 


.SH "Member Data Documentation"
.PP 
.SS "GameObject win\&.Car"

.SS "\fBcarmoveinmap\fP win\&.carmove"

.SS "GameObject win\&.enemy"

.SS "GameObject win\&.Gameover"

.SS "\fBtimer\fP win\&.timescript"

.SS "\fBUImanager\fP win\&.ui"

.SS "GameObject win\&.Winner"


.SH "Author"
.PP 
Generated automatically by Doxygen for FLASH from the source code\&.
