var annotated_dup =
[
    [ "AISimple", "class_a_i_simple.html", "class_a_i_simple" ],
    [ "Audiomanager", "class_audiomanager.html", "class_audiomanager" ],
    [ "camercontroll", "classcamercontroll.html", "classcamercontroll" ],
    [ "CarChange", "class_car_change.html", "class_car_change" ],
    [ "carmoveinmap", "classcarmoveinmap.html", "classcarmoveinmap" ],
    [ "carposition", "classcarposition.html", "classcarposition" ],
    [ "change_obj", "classchange__obj.html", "classchange__obj" ],
    [ "enemy_car", "classenemy__car.html", "classenemy__car" ],
    [ "EnemyAI", "class_enemy_a_i.html", "class_enemy_a_i" ],
    [ "EnemyDestroyer", "class_enemy_destroyer.html", null ],
    [ "enemypath", "classenemypath.html", null ],
    [ "Highscore", "class_highscore.html", "class_highscore" ],
    [ "levelunlock", "classlevelunlock.html", "classlevelunlock" ],
    [ "move", "classmove.html", "classmove" ],
    [ "Music", "class_music.html", "class_music" ],
    [ "musiconoff", "classmusiconoff.html", "classmusiconoff" ],
    [ "NetwokManager_Custom", "class_netwok_manager___custom.html", "class_netwok_manager___custom" ],
    [ "playerallscene", "classplayerallscene.html", null ],
    [ "Quit", "class_quit.html", "class_quit" ],
    [ "SceneChange", "class_scene_change.html", "class_scene_change" ],
    [ "Sound_change", "class_sound__change.html", "class_sound__change" ],
    [ "timer", "classtimer.html", "classtimer" ],
    [ "UImanager", "class_u_imanager.html", "class_u_imanager" ],
    [ "win", "classwin.html", "classwin" ]
];